# server configuration
server:
  servlet:
    context-path: /selfManagement
  port: 8080

# spring  configuration
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306//focus
    username: root
    password: root

# mybatis configuration
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl